apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-deployment.yaml
  - backstage-secret.yaml
  - backstage-deployment.yaml
